### List all messages
GET http://localhost:3000/messages

### Create Message
POST http://localhost:3000/messages
content-type: application/json

{
"content":"sec message"
}


### Get Message
GET http://localhost:3000/messages/96555
